# Generated by Django 3.1 on 2020-08-20 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review',
            field=models.TextField(default=datetime.datetime(2020, 8, 20, 22, 5, 24, 899654, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
