# Generated by Django 3.1 on 2020-09-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_productreview_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.RenameField(
            model_name='productsupplier',
            old_name='profile_picture',
            new_name='profilProductReviewe_picture',
        ),
    ]
