# Generated by Django 3.1 on 2020-09-23 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20200917_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=datetime.datetime(2020, 9, 23, 21, 9, 0, 119723, tzinfo=utc), upload_to='gallery'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
